name: reviewers

on: pull_request 
  branches:
    - master
  jobs:
    ask_reviewers:
      name: 'ask_reviewers'
      runs-on: ubuntu-latest
      steps:

      # addReviewers: true
      # addAssignees: author

      # reviewers:
      #   - jessearaujo93
      #   - pardorafaela

      # skipKeywords:
      #   - wip

      # numberOfReviewers: 1